// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gtk2YhE2bnetxMHveLfNn55Rmet_wPc',
    appId: '1:755618363315:web:a8fd9c2970ed959d21fdc6',
    messagingSenderId: '755618363315',
    projectId: 'utrgv-campus-connect',
    authDomain: 'utrgv-campus-connect.firebaseapp.com',
    storageBucket: 'utrgv-campus-connect.firebasestorage.app',
    measurementId: 'G-LNNB0PQ3TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwttjvg85wA7gRuyym0Xxs6H1lkKvwpEM',
    appId: '1:755618363315:android:47677961644745a721fdc6',
    messagingSenderId: '755618363315',
    projectId: 'utrgv-campus-connect',
    storageBucket: 'utrgv-campus-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsIG3OvHPHVTehK2pvcHHFFNPVYd_XLmA',
    appId: '1:755618363315:ios:19420b6acb4673ee21fdc6',
    messagingSenderId: '755618363315',
    projectId: 'utrgv-campus-connect',
    storageBucket: 'utrgv-campus-connect.firebasestorage.app',
    iosBundleId: 'com.example.utrgvCampusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsIG3OvHPHVTehK2pvcHHFFNPVYd_XLmA',
    appId: '1:755618363315:ios:19420b6acb4673ee21fdc6',
    messagingSenderId: '755618363315',
    projectId: 'utrgv-campus-connect',
    storageBucket: 'utrgv-campus-connect.firebasestorage.app',
    iosBundleId: 'com.example.utrgvCampusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6gtk2YhE2bnetxMHveLfNn55Rmet_wPc',
    appId: '1:755618363315:web:7b4faf1cbbe70f0821fdc6',
    messagingSenderId: '755618363315',
    projectId: 'utrgv-campus-connect',
    authDomain: 'utrgv-campus-connect.firebaseapp.com',
    storageBucket: 'utrgv-campus-connect.firebasestorage.app',
    measurementId: 'G-48Q8SEDK4F',
  );
}
